### ISSUE TITLE
`export CT_APP_MS_ADDR` does not work

### ISSUE THREAD

**Issue by felicityin** [hedzr/consul-tags#8]
`export CT_APP_MS_ADDR=20.120.34.130:8500` does not work:
```
wget https://github.com/hedzr/consul-tags/releases/download/v0.7.3/consul-tags-linux-amd64.tgz
tar -xvzf consul-tags-linux-amd64.tgz

cd bin
export CT_APP_MS_ADDR=20.120.34.130:8500

./consul-tags ms ls tags --name 6

ERRO [2024-10-24 18:01:19.535434] qm: <nil>, err: Get "http://:0/v1/catalog/services": dial tcp :0: connect: connection refused github.com/hedzr/consul-tags/objects/consul/services.go:25 GH/hedzr/consul-tags/objects/consul.listServices.func1() 
```

**Comment by hedzr** [comment]
hi, i checked the codes and found these points:

1. About yours, `./consul-tags ms tags ...` could be what you want? rather than `./consul-tags ms ls ...`.
2. In my old codes, it used an early cmdr. So a quite big rewriting perhaps have to be scheduled. I mean, this will takes more time to fix the issue if it's really there.

I hope lucky if the point 1 can make you happy and ready for the further feedback.

**Comment by felicityin** [comment]
@hedzr  I want to list services or list tags. The consul url should be 20.120.34.130:8500, but according to the printed log, it is empty: "http://:0/v1/catalog/services".

```
export CT_APP_MS_ADDR=20.120.34.130:8500

./consul-tags ms ls

ERRO [2024-10-24 20:00:48.025967] qm: <nil>, err: Get "http://:0/v1/catalog/services": dial tcp :0: connect: connection refused github.com/hedzr/consul-tags/objects/consul/services.go:25 GH/hedzr/consul-tags/objects/consul.listServices.func1() 

```

**Comment by hedzr** [comment]
i'll try. Keep eyes pls.
Thanks for your time.

**Comment by felicityin** [comment]
@hedzr  Thanks!

**Comment by hedzr** [comment]
i'm releasing a new version but i'm not sure whether the workflow could work properly.
if the binaries are not generated, you can make build from the new codes.

**Comment by hedzr** [comment]
well, so bad the packaging failed.
i'll release it manually later.
as for the fixing about workflow scripts, the patches would be delayed till the next patch version.

**Comment by felicityin** [comment]
@hedzr It worked! Thanks!
